### PR TITLE
feat: update to testng 7.6.1

### PR DESCRIPTION
**Pull request by missedone**

### CODE REVIEW

**Comment by krmahadevan** [comment]
@missedone - Do you think we should wait for maybe `7.6.1` (bug fix release) to go out before we update this? The bug is not a major one, but it broke the capability of being able to run tests that are embedded in a test jar, via an xml that is also embedded in the jar.

**Comment by missedone** [comment]
@krmahadevan sounds good, i can have quick test if 7.6.1-SNAPSHOT is available

**Comment by krmahadevan** [comment]
@missedone - Its published https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/7.6.1-SNAPSHOT/

and oh btw, this is the defect that was found and fixed for this possible bug fix release https://github.com/cbeust/testng/issues/2761

@juherr - What is your opinion on the bugfix release ? Shall we proceed further with it ? `7.6.1`

**Comment by juherr** [comment]
I'm not sure the broken feature is used a lot.

But if you plan the fix soon, it will be better to wait and make the effort once.

**Comment by juherr** [comment]
You can make the release you want.

The current version is good too me.
If it takes too much effort to make a release now and another for the fix, you can wait.

You choose.

**Comment by krmahadevan** [comment]
@juherr - I think I will want to use this opportunity to make a bug fix release `7.6.1` with just this fix so that I can test out all the recommendations that Vlad has been sharing in terms of how to use the release plugin. It will be a good exercise to streamline and document the final release process as well. WDYT ?

**Comment by krmahadevan** [comment]
@juherr @missedone `7.6.1` has been released

**Comment by missedone** [comment]
@krmahadevan thanks for the release, the testng-p2 release is available here https://github.com/testng-team/testng-p2-update-site/pull/2

**Review by krmahadevan — APPROVED** [review]

**Pull request merged**
