### PR TITLE
fix unexpected dependency 'guice'

### PR DESCRIPTION
**Pull request by missedone**
the testng-7.0.0-beta2 generates extra unexpected depeendecies, remove them
screenshot at jan 01 03-34-39

### CODE REVIEW

**Comment by missedone** [comment]
well, it's not really an issue, but since 7.0.0-beta2, it generates more optional dependencies (due to the `Export-Package` in MANIFEST.MF), while they are not before.
i want to keep as it is before, don't want to have these extra optional jars generated in the p2 repo.

**Comment by juherr** [comment]
@missedone Do you think we should fix it in cbeust/testng too?

**Comment by missedone** [comment]
@juherr
I'm not sure what's the impact to the users.
But it looks to me better to fix in testing because normally we just export the own packages (saying `org.test...` , the thirtld party lib should have its own export directive.

**Comment by missedone** [comment]
> Can we use testng-p2 as official osgi repository?

That was the goal of testng-p2.

But I'm not sure what the compatibility level testng-p2 offers, I haven't yet verified it in any OSGi framework except Eclipse.
We need the community effort to verify testng-p2 in this case. But I don't see any request come in before.

There is one more thing, we need to publish this osgified testing to Maven repo as some user manages OSGi dependency with Maven.

**Comment by juherr** [comment]
Ok. What do you think if we remove the 3rd party references and add a link to testng-p2 into the documentation?

At the same time, I found the following:
> Because TestNG is not an OSGi Bundle, you have to provide the TestNG classes and it's dependencies (currently only com.beust.jcommander) as OSGi bundles by either include the jars into your test plugin and export the TestNG java packages so that the Tycho Surefire Plugin can see them or create a separate Eclipse Plug-in ("Plug-in from Existing JAR Archives" Wizard) that contains the jars. Make sure the TestNG java packages are exported. Add this newly created Plug-in as a dependency to all your Test Plug-ins /Fragments.

https://wiki.eclipse.org/Tycho/Release_Notes/0.26

Any idea why they say TestNG is not a OSGi Bundle?

**Comment by missedone** [comment]
> What do you think if we remove the 3rd party references and add a link to testng-p2 into the documentation?

yes, this might redirect the users to testng-p2

> Any idea why they say TestNG is not a OSGi Bundle?

I have no idea...
@mbooth101, do you happen the know any info?
or, we might email the tycho team to ask if they met any tech issue with using TestNG in OSGi system.

**Comment by mbooth101** [comment]
> https://wiki.eclipse.org/Tycho/Release_Notes/0.26
> 
> Any idea why they say TestNG is not a OSGi Bundle?

Because the release notes for Tycho 0.26 are super old and pre-dates the OSGi-fication of TestNG.

**Comment by juherr** [comment]
@mbooth101 Thanks for your answer. 
The 0.26 version is very old but the newer release notes don't explicitly say that the previous workaround is useless now. :)

**Comment by mbooth101** [comment]
Fair enough. If TestNG is fully available as an OSGi bundle, such workarounds are no longer necessary :-)

**Comment by missedone** [comment]
@mbooth101
We are also discussing if make testing-p2 the official testng osgi bundle 
But we are lack of verification from the community.

**Pull request merged**
